/**
 * 自动扫描 src/components 下的子目录，生成 components/index.ts
 * 约定：每个组件目录名即为导出名（PascalCase），目录下有 index.ts 或 index.vue
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const componentsDir = path.resolve(__dirname, '../src/components')
const outputFile = path.resolve(componentsDir, 'index.ts')

const dirs = fs.readdirSync(componentsDir, { withFileTypes: true })
  .filter(d => d.isDirectory())
  .map(d => d.name)
  .filter(name => {
    // 确保目录下存在 index.ts 或 index.vue
    return (
      fs.existsSync(path.join(componentsDir, name, 'index.ts')) ||
      fs.existsSync(path.join(componentsDir, name, 'index.vue'))
    )
  })
  .sort()

const lines = [
  '// Auto-generated by scripts/gen-components.ts — DO NOT EDIT',
  '',
  ...dirs.map(name => `export { default as ${name} } from './${name}'`),
  '',
]

fs.writeFileSync(outputFile, lines.join('\n'), 'utf-8')
console.log(`✅ Generated components/index.ts with ${dirs.length} components: ${dirs.join(', ')}`)
