/**
 * 自动扫描 src/components 下的子目录，生成 components/index.ts
 * 同时为 src/styles/index.less 汇总所有组件样式
 * 约定：每个组件目录名即为导出名（PascalCase），目录下有 index.ts 或 index.vue
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const componentsDir = path.resolve(__dirname, '../src/components')
const outputFile = path.resolve(componentsDir, 'index.ts')
const stylesOutputFile = path.resolve(__dirname, '../src/styles/index.less')

const dirs = fs.readdirSync(componentsDir, { withFileTypes: true })
  .filter(d => d.isDirectory())
  .map(d => d.name)
  .filter(name => {
    // 确保目录下存在 index.ts 或 index.vue
    return (
      fs.existsSync(path.join(componentsDir, name, 'index.ts')) ||
      fs.existsSync(path.join(componentsDir, name, 'index.vue'))
    )
  })
  .sort()

// ---- 生成 components/index.ts ----
const lines = [
  '// Auto-generated by scripts/gen-components.ts — DO NOT EDIT',
  '',
  ...dirs.map(name => `export { default as ${name} } from './${name}'`),
  '',
]

fs.writeFileSync(outputFile, lines.join('\n'), 'utf-8')
console.log(`✅ Generated components/index.ts with ${dirs.length} components: ${dirs.join(', ')}`)

// ---- 生成 styles/index.less（汇总组件样式）----
// const styleImports = dirs
//   .filter(name => fs.existsSync(path.join(componentsDir, name, 'style', 'index.less')))
//   .map(name => `@import '../components/${name}/style/index.less';`)

// const styleLines = [
//   '// Auto-generated by scripts/gen-components.ts — DO NOT EDIT',
//   '',
//   '// ---- 全局基础样式 ----',
//   'html,',
//   'body {',
//   '  width: 100%;',
//   '  height: 100%;',
//   '}',
//   'input::-ms-clear,',
//   'input::-ms-reveal {',
//   '  display: none;',
//   '}',
//   '*,',
//   '*::before,',
//   '*::after {',
//   '  box-sizing: border-box;',
//   '}',
//   '',
//   '// ---- 组件样式汇总 ----',
//   ...styleImports,
//   '',
// ]

// fs.writeFileSync(stylesOutputFile, styleLines.join('\n'), 'utf-8')
// console.log(`✅ Generated styles/index.less with ${styleImports.length} component styles`)
